import {escape as e,json} from '../lib/html.mjs';
export const origin='https://apistopalace.com';
const nav=['Species','Finder','Care','Breeding','Habitats','Identify','Comparisons','Articles'];
export function layout({path,title,description,body,type='WebPage',index=true,crumbs=[],production=false}){
const url=origin+path; const breadcrumb=[{name:'Home',path:'/'},...crumbs];
const graph=[{'@type':path==='/'?'WebSite':type,'@id':url,name:title,url,description,inLanguage:'en',...(type==='Article'?{headline:title,datePublished:'2026-09-24',dateModified:'2026-09-24',author:{'@type':'Organization',name:'ApistoPalace'},publisher:{'@type':'Organization',name:'ApistoPalace'},mainEntityOfPage:url}: {})},...(path!=='/'?[{'@type':'BreadcrumbList',itemListElement:breadcrumb.map((b,i)=>({'@type':'ListItem',position:i+1,name:b.name,item:origin+b.path}))}]:[])];
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | ApistoPalace</title><meta name="description" content="${e(description)}"><meta name="robots" content="${production?(index?'index,follow':'noindex,follow'):'noindex,nofollow'}"><link rel="canonical" href="${url}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${type==='Article'?'article':'website'}"><meta property="og:url" content="${url}"><meta name="theme-color" content="#102923"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':graph})}</script><script type="module" src="/app.mjs"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a href="/" class="brand" aria-label="ApistoPalace home"><span class="brand-mark" aria-hidden="true">A<span>✦</span></span><span>APISTO<span class="brand-light">PALACE</span><small>A FIELD GUIDE TO THE GENUS</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="navigation" hidden>Menu</button><nav id="navigation" aria-label="Main navigation">${nav.map(n=>`<a href="/${n.toLowerCase()}/" ${path.startsWith('/'+n.toLowerCase()+'/')?'aria-current="page"':''}>${n}</a>`).join('')}</nav></header><main id="main">${path!=='/'?`<nav class="breadcrumbs wrap" aria-label="Breadcrumb"><ol>${breadcrumb.map((b,i)=>`<li>${i===breadcrumb.length-1?`<span aria-current="page">${e(b.name)}</span>`:`<a href="${b.path}">${e(b.name)}</a>`}</li>`).join('')}</ol></nav>`:''}${body}</main><footer><div class="wrap footer-grid"><div><a class="footer-brand" href="/">APISTOPALACE</a><p>A closer look at a remarkable genus.<br>Explore thoughtfully. Keep responsibly.</p></div><div><strong>The field guide</strong><a href="/species/">Browse species</a><a href="/finder/">Find your Apisto</a><a href="/habitats/">Explore habitats</a></div><div><strong>About this collection</strong><a href="/about/">Editorial approach & sources</a><a href="/credits/">Photography credits</a><a href="/comparisons/">Compare species</a></div></div><div class="wrap footer-bottom"><span>© 2026 ApistoPalace · An independent field guide in the PetZoneSD network</span><span>South America, one species at a time.</span></div></footer></body></html>`;
}
export function heading(eyebrow,title,intro){return `<header class="page-heading wrap"><p class="eyebrow">${e(eyebrow)}</p><h1>${e(title)}</h1><p class="lede">${e(intro)}</p></header>`}
export function prose(sections){return sections.map(([h,p],i)=>`<section id="section-${i+1}"><h2>${e(h)}</h2><p>${e(p)}</p></section>`).join('')}
